//
// CallScriptType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace XMLRules
{
	public class CallScriptType : Altova.Node
	{
		#region Forward constructors
		public CallScriptType() : base() { SetCollectionParents(); }
		public CallScriptType(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public CallScriptType(XmlNode node) : base(node) { SetCollectionParents(); }
		public CallScriptType(Altova.Node node) : base(node) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{
			int nCount;

			nCount = DomChildCount(NodeType.Element, "", "ScriptName");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ScriptName", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			nCount = DomChildCount(NodeType.Element, "", "ScriptParameter");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ScriptParameter", i);
				InternalAdjustPrefix(DOMNode, true);
				new Value(DOMNode).AdjustPrefix();
			}
		}


		#region ScriptName accessor methods
		public int GetScriptNameMinCount()
		{
			return 1;
		}

		public int ScriptNameMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetScriptNameMaxCount()
		{
			return 1;
		}

		public int ScriptNameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetScriptNameCount()
		{
			return DomChildCount(NodeType.Element, "", "ScriptName");
		}

		public int ScriptNameCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ScriptName");
			}
		}

		public bool HasScriptName()
		{
			return HasDomChild(NodeType.Element, "", "ScriptName");
		}

		public SchemaString GetScriptNameAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "ScriptName", index)));
		}

		public SchemaString GetScriptName()
		{
			return GetScriptNameAt(0);
		}

		public SchemaString ScriptName
		{
			get
			{
				return GetScriptNameAt(0);
			}
		}

		public void RemoveScriptNameAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ScriptName", index);
		}

		public void RemoveScriptName()
		{
			while (HasScriptName())
				RemoveScriptNameAt(0);
		}

		public void AddScriptName(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "ScriptName", newValue.ToString());
		}

		public void InsertScriptNameAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "ScriptName", index, newValue.ToString());
		}

		public void ReplaceScriptNameAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "ScriptName", index, newValue.ToString());
		}
		#endregion // ScriptName accessor methods

		#region ScriptName collection
        public ScriptNameCollection	MyScriptNames = new ScriptNameCollection( );

        public class ScriptNameCollection: IEnumerable
        {
            CallScriptType parent;
            public CallScriptType Parent
			{
				set
				{
					parent = value;
				}
			}
			public ScriptNameEnumerator GetEnumerator() 
			{
				return new ScriptNameEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ScriptNameEnumerator: IEnumerator 
        {
			int nIndex;
			CallScriptType parent;
			public ScriptNameEnumerator(CallScriptType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ScriptNameCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetScriptNameAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // ScriptName collection

		#region ScriptParameter accessor methods
		public int GetScriptParameterMinCount()
		{
			return 0;
		}

		public int ScriptParameterMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetScriptParameterMaxCount()
		{
			return Int32.MaxValue;
		}

		public int ScriptParameterMaxCount
		{
			get
			{
				return Int32.MaxValue;
			}
		}

		public int GetScriptParameterCount()
		{
			return DomChildCount(NodeType.Element, "", "ScriptParameter");
		}

		public int ScriptParameterCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ScriptParameter");
			}
		}

		public bool HasScriptParameter()
		{
			return HasDomChild(NodeType.Element, "", "ScriptParameter");
		}

		public Value GetScriptParameterAt(int index)
		{
			return new Value(GetDomChildAt(NodeType.Element, "", "ScriptParameter", index));
		}

		public Value GetScriptParameter()
		{
			return GetScriptParameterAt(0);
		}

		public Value ScriptParameter
		{
			get
			{
				return GetScriptParameterAt(0);
			}
		}

		public void RemoveScriptParameterAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ScriptParameter", index);
		}

		public void RemoveScriptParameter()
		{
			while (HasScriptParameter())
				RemoveScriptParameterAt(0);
		}

		public void AddScriptParameter(Value newValue)
		{
			AppendDomElement("", "ScriptParameter", newValue);
		}

		public void InsertScriptParameterAt(Value newValue, int index)
		{
			InsertDomElementAt("", "ScriptParameter", index, newValue);
		}

		public void ReplaceScriptParameterAt(Value newValue, int index)
		{
			ReplaceDomElementAt("", "ScriptParameter", index, newValue);
		}
		#endregion // ScriptParameter accessor methods

		#region ScriptParameter collection
        public ScriptParameterCollection	MyScriptParameters = new ScriptParameterCollection( );

        public class ScriptParameterCollection: IEnumerable
        {
            CallScriptType parent;
            public CallScriptType Parent
			{
				set
				{
					parent = value;
				}
			}
			public ScriptParameterEnumerator GetEnumerator() 
			{
				return new ScriptParameterEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ScriptParameterEnumerator: IEnumerator 
        {
			int nIndex;
			CallScriptType parent;
			public ScriptParameterEnumerator(CallScriptType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ScriptParameterCount );
			}
			public Value  Current 
			{
				get 
				{
					return(parent.GetScriptParameterAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // ScriptParameter collection

        private void SetCollectionParents()
        {
            MyScriptNames.Parent = this; 
            MyScriptParameters.Parent = this; 
	}
}
}
