//
// ParameterType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace XMLRules
{
	public class ParameterType : Altova.Node
	{
		#region Forward constructors
		public ParameterType() : base() { SetCollectionParents(); }
		public ParameterType(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public ParameterType(XmlNode node) : base(node) { SetCollectionParents(); }
		public ParameterType(Altova.Node node) : base(node) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{
			int nCount;

			nCount = DomChildCount(NodeType.Element, "", "Name");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Name", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			nCount = DomChildCount(NodeType.Element, "", "Type");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Type", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			nCount = DomChildCount(NodeType.Element, "", "Value");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Value", i);
				InternalAdjustPrefix(DOMNode, true);
				new ConstantType(DOMNode).AdjustPrefix();
			}
		}


		#region Name accessor methods
		public int GetNameMinCount()
		{
			return 1;
		}

		public int NameMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameMaxCount()
		{
			return 1;
		}

		public int NameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameCount()
		{
			return DomChildCount(NodeType.Element, "", "Name");
		}

		public int NameCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Name");
			}
		}

		public bool HasName()
		{
			return HasDomChild(NodeType.Element, "", "Name");
		}

		public SchemaString GetNameAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "Name", index)));
		}

		public SchemaString GetName()
		{
			return GetNameAt(0);
		}

		public SchemaString Name
		{
			get
			{
				return GetNameAt(0);
			}
		}

		public void RemoveNameAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Name", index);
		}

		public void RemoveName()
		{
			while (HasName())
				RemoveNameAt(0);
		}

		public void AddName(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "Name", newValue.ToString());
		}

		public void InsertNameAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "Name", index, newValue.ToString());
		}

		public void ReplaceNameAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "Name", index, newValue.ToString());
		}
		#endregion // Name accessor methods

		#region Name collection
        public NameCollection	MyNames = new NameCollection( );

        public class NameCollection: IEnumerable
        {
            ParameterType parent;
            public ParameterType Parent
			{
				set
				{
					parent = value;
				}
			}
			public NameEnumerator GetEnumerator() 
			{
				return new NameEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class NameEnumerator: IEnumerator 
        {
			int nIndex;
			ParameterType parent;
			public NameEnumerator(ParameterType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.NameCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetNameAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // Name collection

		#region Type2 accessor methods
		public int GetType2MinCount()
		{
			return 1;
		}

		public int Type2MinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetType2MaxCount()
		{
			return 1;
		}

		public int Type2MaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetType2Count()
		{
			return DomChildCount(NodeType.Element, "", "Type");
		}

		public int Type2Count
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Type");
			}
		}

		public bool HasType2()
		{
			return HasDomChild(NodeType.Element, "", "Type");
		}

		public SchemaString GetType2At(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "Type", index)));
		}

		public SchemaString GetType2()
		{
			return GetType2At(0);
		}

		public SchemaString Type2
		{
			get
			{
				return GetType2At(0);
			}
		}

		public void RemoveType2At(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Type", index);
		}

		public void RemoveType2()
		{
			while (HasType2())
				RemoveType2At(0);
		}

		public void AddType2(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "Type", newValue.ToString());
		}

		public void InsertType2At(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "Type", index, newValue.ToString());
		}

		public void ReplaceType2At(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "Type", index, newValue.ToString());
		}
		#endregion // Type2 accessor methods

		#region Type2 collection
        public Type2Collection	MyType2s = new Type2Collection( );

        public class Type2Collection: IEnumerable
        {
            ParameterType parent;
            public ParameterType Parent
			{
				set
				{
					parent = value;
				}
			}
			public Type2Enumerator GetEnumerator() 
			{
				return new Type2Enumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class Type2Enumerator: IEnumerator 
        {
			int nIndex;
			ParameterType parent;
			public Type2Enumerator(ParameterType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.Type2Count );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetType2At(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // Type2 collection

		#region Value accessor methods
		public int GetValueMinCount()
		{
			return 1;
		}

		public int ValueMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetValueMaxCount()
		{
			return 1;
		}

		public int ValueMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetValueCount()
		{
			return DomChildCount(NodeType.Element, "", "Value");
		}

		public int ValueCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Value");
			}
		}

		public bool HasValue()
		{
			return HasDomChild(NodeType.Element, "", "Value");
		}

		public ConstantType GetValueAt(int index)
		{
			return new ConstantType(GetDomChildAt(NodeType.Element, "", "Value", index));
		}

		public ConstantType GetValue()
		{
			return GetValueAt(0);
		}

		public ConstantType Value
		{
			get
			{
				return GetValueAt(0);
			}
		}

		public void RemoveValueAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Value", index);
		}

		public void RemoveValue()
		{
			while (HasValue())
				RemoveValueAt(0);
		}

		public void AddValue(ConstantType newValue)
		{
			AppendDomElement("", "Value", newValue);
		}

		public void InsertValueAt(ConstantType newValue, int index)
		{
			InsertDomElementAt("", "Value", index, newValue);
		}

		public void ReplaceValueAt(ConstantType newValue, int index)
		{
			ReplaceDomElementAt("", "Value", index, newValue);
		}
		#endregion // Value accessor methods

		#region Value collection
        public ValueCollection	MyValues = new ValueCollection( );

        public class ValueCollection: IEnumerable
        {
            ParameterType parent;
            public ParameterType Parent
			{
				set
				{
					parent = value;
				}
			}
			public ValueEnumerator GetEnumerator() 
			{
				return new ValueEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ValueEnumerator: IEnumerator 
        {
			int nIndex;
			ParameterType parent;
			public ValueEnumerator(ParameterType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ValueCount );
			}
			public ConstantType  Current 
			{
				get 
				{
					return(parent.GetValueAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // Value collection

        private void SetCollectionParents()
        {
            MyNames.Parent = this; 
            MyType2s.Parent = this; 
            MyValues.Parent = this; 
	}
}
}
