//
// SubExpressionType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace XMLRules
{
	public class SubExpressionType : Altova.Node
	{
		#region Forward constructors
		public SubExpressionType() : base() { SetCollectionParents(); }
		public SubExpressionType(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public SubExpressionType(XmlNode node) : base(node) { SetCollectionParents(); }
		public SubExpressionType(Altova.Node node) : base(node) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{
			int nCount;

			nCount = DomChildCount(NodeType.Element, "", "LHSArithmeticExpression");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "LHSArithmeticExpression", i);
				InternalAdjustPrefix(DOMNode, true);
				new ArithmeticExpression(DOMNode).AdjustPrefix();
			}

			nCount = DomChildCount(NodeType.Element, "", "ArithmeticOperator");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ArithmeticOperator", i);
				InternalAdjustPrefix(DOMNode, true);
				new ArithemticOperator(DOMNode).AdjustPrefix();
			}

			nCount = DomChildCount(NodeType.Element, "", "RHSArithmeticExpression");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "RHSArithmeticExpression", i);
				InternalAdjustPrefix(DOMNode, true);
				new ArithmeticExpression(DOMNode).AdjustPrefix();
			}
		}


		#region LHSArithmeticExpression accessor methods
		public int GetLHSArithmeticExpressionMinCount()
		{
			return 1;
		}

		public int LHSArithmeticExpressionMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLHSArithmeticExpressionMaxCount()
		{
			return 1;
		}

		public int LHSArithmeticExpressionMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLHSArithmeticExpressionCount()
		{
			return DomChildCount(NodeType.Element, "", "LHSArithmeticExpression");
		}

		public int LHSArithmeticExpressionCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "LHSArithmeticExpression");
			}
		}

		public bool HasLHSArithmeticExpression()
		{
			return HasDomChild(NodeType.Element, "", "LHSArithmeticExpression");
		}

		public ArithmeticExpression GetLHSArithmeticExpressionAt(int index)
		{
			return new ArithmeticExpression(GetDomChildAt(NodeType.Element, "", "LHSArithmeticExpression", index));
		}

		public ArithmeticExpression GetLHSArithmeticExpression()
		{
			return GetLHSArithmeticExpressionAt(0);
		}

		public ArithmeticExpression LHSArithmeticExpression
		{
			get
			{
				return GetLHSArithmeticExpressionAt(0);
			}
		}

		public void RemoveLHSArithmeticExpressionAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "LHSArithmeticExpression", index);
		}

		public void RemoveLHSArithmeticExpression()
		{
			while (HasLHSArithmeticExpression())
				RemoveLHSArithmeticExpressionAt(0);
		}

		public void AddLHSArithmeticExpression(ArithmeticExpression newValue)
		{
			AppendDomElement("", "LHSArithmeticExpression", newValue);
		}

		public void InsertLHSArithmeticExpressionAt(ArithmeticExpression newValue, int index)
		{
			InsertDomElementAt("", "LHSArithmeticExpression", index, newValue);
		}

		public void ReplaceLHSArithmeticExpressionAt(ArithmeticExpression newValue, int index)
		{
			ReplaceDomElementAt("", "LHSArithmeticExpression", index, newValue);
		}
		#endregion // LHSArithmeticExpression accessor methods

		#region LHSArithmeticExpression collection
        public LHSArithmeticExpressionCollection	MyLHSArithmeticExpressions = new LHSArithmeticExpressionCollection( );

        public class LHSArithmeticExpressionCollection: IEnumerable
        {
            SubExpressionType parent;
            public SubExpressionType Parent
			{
				set
				{
					parent = value;
				}
			}
			public LHSArithmeticExpressionEnumerator GetEnumerator() 
			{
				return new LHSArithmeticExpressionEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class LHSArithmeticExpressionEnumerator: IEnumerator 
        {
			int nIndex;
			SubExpressionType parent;
			public LHSArithmeticExpressionEnumerator(SubExpressionType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.LHSArithmeticExpressionCount );
			}
			public ArithmeticExpression  Current 
			{
				get 
				{
					return(parent.GetLHSArithmeticExpressionAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // LHSArithmeticExpression collection

		#region ArithmeticOperator accessor methods
		public int GetArithmeticOperatorMinCount()
		{
			return 1;
		}

		public int ArithmeticOperatorMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetArithmeticOperatorMaxCount()
		{
			return 1;
		}

		public int ArithmeticOperatorMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetArithmeticOperatorCount()
		{
			return DomChildCount(NodeType.Element, "", "ArithmeticOperator");
		}

		public int ArithmeticOperatorCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ArithmeticOperator");
			}
		}

		public bool HasArithmeticOperator()
		{
			return HasDomChild(NodeType.Element, "", "ArithmeticOperator");
		}

		public ArithemticOperator GetArithmeticOperatorAt(int index)
		{
			return new ArithemticOperator(GetDomChildAt(NodeType.Element, "", "ArithmeticOperator", index));
		}

		public ArithemticOperator GetArithmeticOperator()
		{
			return GetArithmeticOperatorAt(0);
		}

		public ArithemticOperator ArithmeticOperator
		{
			get
			{
				return GetArithmeticOperatorAt(0);
			}
		}

		public void RemoveArithmeticOperatorAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ArithmeticOperator", index);
		}

		public void RemoveArithmeticOperator()
		{
			while (HasArithmeticOperator())
				RemoveArithmeticOperatorAt(0);
		}

		public void AddArithmeticOperator(ArithemticOperator newValue)
		{
			AppendDomElement("", "ArithmeticOperator", newValue);
		}

		public void InsertArithmeticOperatorAt(ArithemticOperator newValue, int index)
		{
			InsertDomElementAt("", "ArithmeticOperator", index, newValue);
		}

		public void ReplaceArithmeticOperatorAt(ArithemticOperator newValue, int index)
		{
			ReplaceDomElementAt("", "ArithmeticOperator", index, newValue);
		}
		#endregion // ArithmeticOperator accessor methods

		#region ArithmeticOperator collection
        public ArithmeticOperatorCollection	MyArithmeticOperators = new ArithmeticOperatorCollection( );

        public class ArithmeticOperatorCollection: IEnumerable
        {
            SubExpressionType parent;
            public SubExpressionType Parent
			{
				set
				{
					parent = value;
				}
			}
			public ArithmeticOperatorEnumerator GetEnumerator() 
			{
				return new ArithmeticOperatorEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ArithmeticOperatorEnumerator: IEnumerator 
        {
			int nIndex;
			SubExpressionType parent;
			public ArithmeticOperatorEnumerator(SubExpressionType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ArithmeticOperatorCount );
			}
			public ArithemticOperator  Current 
			{
				get 
				{
					return(parent.GetArithmeticOperatorAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // ArithmeticOperator collection

		#region RHSArithmeticExpression accessor methods
		public int GetRHSArithmeticExpressionMinCount()
		{
			return 1;
		}

		public int RHSArithmeticExpressionMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetRHSArithmeticExpressionMaxCount()
		{
			return 1;
		}

		public int RHSArithmeticExpressionMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetRHSArithmeticExpressionCount()
		{
			return DomChildCount(NodeType.Element, "", "RHSArithmeticExpression");
		}

		public int RHSArithmeticExpressionCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "RHSArithmeticExpression");
			}
		}

		public bool HasRHSArithmeticExpression()
		{
			return HasDomChild(NodeType.Element, "", "RHSArithmeticExpression");
		}

		public ArithmeticExpression GetRHSArithmeticExpressionAt(int index)
		{
			return new ArithmeticExpression(GetDomChildAt(NodeType.Element, "", "RHSArithmeticExpression", index));
		}

		public ArithmeticExpression GetRHSArithmeticExpression()
		{
			return GetRHSArithmeticExpressionAt(0);
		}

		public ArithmeticExpression RHSArithmeticExpression
		{
			get
			{
				return GetRHSArithmeticExpressionAt(0);
			}
		}

		public void RemoveRHSArithmeticExpressionAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "RHSArithmeticExpression", index);
		}

		public void RemoveRHSArithmeticExpression()
		{
			while (HasRHSArithmeticExpression())
				RemoveRHSArithmeticExpressionAt(0);
		}

		public void AddRHSArithmeticExpression(ArithmeticExpression newValue)
		{
			AppendDomElement("", "RHSArithmeticExpression", newValue);
		}

		public void InsertRHSArithmeticExpressionAt(ArithmeticExpression newValue, int index)
		{
			InsertDomElementAt("", "RHSArithmeticExpression", index, newValue);
		}

		public void ReplaceRHSArithmeticExpressionAt(ArithmeticExpression newValue, int index)
		{
			ReplaceDomElementAt("", "RHSArithmeticExpression", index, newValue);
		}
		#endregion // RHSArithmeticExpression accessor methods

		#region RHSArithmeticExpression collection
        public RHSArithmeticExpressionCollection	MyRHSArithmeticExpressions = new RHSArithmeticExpressionCollection( );

        public class RHSArithmeticExpressionCollection: IEnumerable
        {
            SubExpressionType parent;
            public SubExpressionType Parent
			{
				set
				{
					parent = value;
				}
			}
			public RHSArithmeticExpressionEnumerator GetEnumerator() 
			{
				return new RHSArithmeticExpressionEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class RHSArithmeticExpressionEnumerator: IEnumerator 
        {
			int nIndex;
			SubExpressionType parent;
			public RHSArithmeticExpressionEnumerator(SubExpressionType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.RHSArithmeticExpressionCount );
			}
			public ArithmeticExpression  Current 
			{
				get 
				{
					return(parent.GetRHSArithmeticExpressionAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // RHSArithmeticExpression collection

        private void SetCollectionParents()
        {
            MyLHSArithmeticExpressions.Parent = this; 
            MyArithmeticOperators.Parent = this; 
            MyRHSArithmeticExpressions.Parent = this; 
	}
}
}
